name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: MatheusPupim
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=blue&color_dots=green,red&bg_color=transparent
            dist/github-contribution-grid-snake-dark.svg?color_snake=blue&color_dots=green,red&bg_color=transparent
            
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
